set-environment -g WORK_END_TIME "17:30"
set-environment -g LUNCH_TIME "12:00"
set-environment -g LUNCH_DURATION "60"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 0
set -g focus-events on
setw -g automatic-rename on
set -g base-index 1
set -g renumber-windows on
set -g pane-base-index 1
set -g status-interval 5
set -g status-style bg=default
set -g status-left-length 50
set -g status-left "#(~/.dotfiles/scripts/bin/tmux-statusline)"
set -g status-right ""
set -g window-status-format "#(~/.dotfiles/scripts/bin/tmux-window-format '#{window_id}' '#{window_index}' '0')"
set -g window-status-current-format "#(~/.dotfiles/scripts/bin/tmux-window-format '#{window_id}' '#{window_index}' '1')"
set -g window-status-separator " | "
set -g history-limit 50000
set -g display-time 4000
set -g aggressive-resize on
set -g mouse on

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\S+\/)?g?(view|n?vim?x?)(diff)?$'"
is_opencode="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(node|opencode)$'"

bind F5 source-file ~/.dotfiles/terminal/.config/tmux/tmux.conf \; display-message "Config reloaded!"
bind \; command-prompt
bind c neww -c "#{pane_current_path}"
bind C-c neww -c "#{pane_current_path}"
bind -n C-M-a swap-window -t -1 \; select-window -t -1
bind -n C-M-x swap-window -t +1 \; select-window -t +1

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'Morantron/tmux-fingers'

# tmux-resurrect: Save/restore sessions
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# tmux-continuum: Auto-save sessions
set -g @continuum-restore 'off'
set -g @continuum-save-interval '15'

# tmux-fingers:
# Add your tmux-fingers configuration here.
set -g @fingers-key 'y'
set -g @fingers-hint-style 'fg=yellow,bg=black,bold'

run '~/.local/share/tmux/plugins/tpm/tpm'
