# Capabilites
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 0
set -g focus-events on
set -g mouse on

# Preferences
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
setw -g automatic-rename on

# Statusline
set -g @git_status_script "~/.config/tmux/tmux-git-status.awk"
set -g status-interval 5
set -g status-style bg=default
set -g status-position bottom
set -g status-left-length 50
set -g status-left ""
set -g window-status-format "#I"
set -g window-status-current-format "#[fg=colour39]#I"
set -g window-status-separator " "
set -g status-right-length 100
set -g status-right '#[align=absolute-centre]#{?#{==:#{pane_current_command},nvim},#{pane_title},} #[align=right] #(cd #{pane_current_path} && git rev-parse --git-dir >/dev/null 2>&1 && if [ -n "#{@git_status_script}" ] && [ -f "#{@git_status_script}" ]; then git status --porcelain=v1 -b 2>/dev/null | awk -f "#{@git_status_script}"; else echo -n "#[fg=colour39]"; git branch --show-current 2>/dev/null | tr -d "\\n"; echo -n "#[fg=default]"; git diff --quiet || echo -n "*"; echo; fi)'

# Keymaps
bind F5 source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf sourced"
bind c neww -c "#{pane_current_path}" # Stay in cwd
bind C-c neww -c "#{pane_current_path}"
bind '"' splitw -c "#{pane_current_path}"
bind % splitw -h -c "#{pane_current_path}"
bind -r C-n next # Repeatable
bind -r C-p prev
bind -r C-i last
bind -r i last # leave l for vim pane motions
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-pane -L # Repeatable
bind -r C-j select-pane -D
bind -r C-k select-pane -U
bind -r C-l select-pane -R

# Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @plugin 'Morantron/tmux-fingers'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
setenv -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins/'
set -g @plugin 'tmux-plugins/tpm'
run '#{TMUX_PLUGIN_MANAGER_PATH}tpm/tpm'
