# Capabilites
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 0
set -g focus-events on
set -g mouse on

# Preferences
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
setw -g automatic-rename on

# Statusline
set -g status-interval 5
set -g status-position top
set -g status-style bg=default
set -g status-left-length 50
set -g status-left "#[fg=colour240]#(whoami)@#H #{?client_prefix,#[fg=colour226]##,#[fg=colour46]$} #[default]"
set -g window-status-format "#(~/.dotfiles/scripts/bin/tmux-window-format '#{window_id}' '#{window_index}' '0')"
set -g window-status-current-format "#(~/.dotfiles/scripts/bin/tmux-window-format '#{window_id}' '#{window_index}' '1')"
set -g window-status-separator " | "
set -g status-right ""

# Keymaps
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
bind F5 source-file ~/.dotfiles/terminal/.config/tmux/tmux.conf \; display-message "tmux.conf sourced"

bind \; command-prompt
bind c neww -c "#{pane_current_path}"
bind C-c neww -c "#{pane_current_path}"
bind -r C-n next-window
bind -r C-p previous-window
bind -r C-l last-window
bind C-d detach-client
bind C-w choose-window
bind C-s choose-session
bind C-x kill-pane
bind C-z resize-pane -Z
bind C-[ copy-mode
bind C-] paste-buffer
bind C-f command-prompt "find-window '%%'"
bind C-t clock-mode
bind "C-?" list-keys
bind C-i display-message
bind -r C-Space next-layout
bind "C-:" command-prompt
bind C-q display-panes
bind C-r refresh-client
bind "C-!" break-pane
bind C-m select-pane -m
bind -n C-M-a swap-window -t -1 \; select-window -t -1
bind -n C-M-x swap-window -t +1 \; select-window -t +1

# Plugins
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'off'
set -g @continuum-save-interval '15'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

set -g @plugin 'Morantron/tmux-fingers'
set -g @fingers-key 'y'
set -g @fingers-hint-style 'fg=yellow,bg=black,bold'

set -g @plugin 'tmux-plugins/tmux-copycat'

set -g @plugin 'tmux-plugins/tpm'
run '~/.local/share/tmux/plugins/tpm/tpm'
