vim.api.nvim_set_hl(0, "BashGray", {ctermfg = 240, fg = "#585858"})
vim.api.nvim_set_hl(0, "BashBold", {bold = true})
vim.api.nvim_set_hl(0, "BashGreen", {ctermfg = 46, fg = "#00ff5f"})
vim.api.nvim_set_hl(0, "BashYellow", {ctermfg = 226, fg = "#ffff00"})
vim.api.nvim_set_hl(0, "BashYellowBold", {ctermfg = 226, fg = "#ffff00", bold = true})
vim.api.nvim_set_hl(0, "BashRed", {ctermfg = 196, fg = "#ff0000"})
vim.api.nvim_set_hl(0, "BashBlue", {ctermfg = 39, fg = "#00afff"})
vim.api.nvim_set_hl(0, "BashMagenta", {ctermfg = 201, fg = "#ff00ff"})
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "NONE" })
